<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>EPPlusTest</RootNamespace>
    <AssemblyName>EPPlusTest</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>EPPlusTest.snk</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IsTestProject>true</IsTestProject>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <NoWarn>$(NoWarn);CS0219;CS1587;CS1573</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>bin\Release\</OutputPath>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <PlatformTarget>x86</PlatformTarget>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'DevTest'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release 4.0'">
    <OutputPath>bin\Release 4.0\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" Version="3.4.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.18" PrivateAssets="all" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.18" PrivateAssets="all" />
    <PackageReference Include="RhinoMocks" Version="3.6.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPPlus\EPPlus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
    <Reference Include="System.Security" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Vector Drawing.wmf" />
    <EmbeddedResource Include="Resources\Vector Drawing2.wmf" />
    <EmbeddedResource Include="Resources\BitmapImage.gif" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Workbooks\FormulaTest.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Test1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
