<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>OfficeOpenXml</RootNamespace>
    <AssemblyName>EPPlus</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>OpenOfficeXml.snk</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <NoWarn>CS1591;CS0219;CS1587;CS1573;CS0414;CS1572;CS0659;CS1570;CS1584;CS0168</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DocumentationFile>bin\Debug\EPPlus.XML</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>bin\Release\</OutputPath>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <DocumentationFile>bin\Release\EPPlus.XML</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'DevTest'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
</Project>
